-- Server-only OAuth provider connections.
-- Provider access/refresh tokens are AES-GCM encrypted by the Node backend before they reach this table.
-- No client RLS policies are created: only the Supabase service role used by the backend may access rows.

create table if not exists public.integration_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('google', 'microsoft')),
  account_email text,
  access_token_enc text not null,
  refresh_token_enc text,
  token_expires_at timestamptz,
  scope text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

alter table public.integration_connections enable row level security;
revoke all on table public.integration_connections from anon, authenticated;
revoke all on sequence public.integration_connections_id_seq from anon, authenticated;

create index if not exists integration_connections_user_id_idx
  on public.integration_connections (user_id);
